minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)
neo_version=21.1.60
neo_version_range=[21.1,)
loader_version_range=[4,)
mod_id=witherify_skull
mod_name=Witherify Skull
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.radsi
mod_authors=Radsi
mod_description=Converts Skeleton skull into Wither skull by heating.
